// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDkZDHCw8LTtNIBuHPBogzdHlMcyttuRrI',
    appId: '1:960084846767:web:482ccf785cd40cbb81cc5a',
    messagingSenderId: '960084846767',
    projectId: 'finance-c2c0d',
    authDomain: 'finance-c2c0d.firebaseapp.com',
    storageBucket: 'finance-c2c0d.firebasestorage.app',
    measurementId: 'G-541VCQRWWW',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKPksesd_TQaOhyikzIY39EiLa-EVhWqA',
    appId: '1:960084846767:android:33b88e600f6841c881cc5a',
    messagingSenderId: '960084846767',
    projectId: 'finance-c2c0d',
    storageBucket: 'finance-c2c0d.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyArYsidUhwDEmcqFkopxDJNO4BSLCuqTkQ',
    appId: '1:960084846767:ios:868bf43a1aca7ca881cc5a',
    messagingSenderId: '960084846767',
    projectId: 'finance-c2c0d',
    storageBucket: 'finance-c2c0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyArYsidUhwDEmcqFkopxDJNO4BSLCuqTkQ',
    appId: '1:960084846767:ios:868bf43a1aca7ca881cc5a',
    messagingSenderId: '960084846767',
    projectId: 'finance-c2c0d',
    storageBucket: 'finance-c2c0d.firebasestorage.app',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDkZDHCw8LTtNIBuHPBogzdHlMcyttuRrI',
    appId: '1:960084846767:web:11ae5dccc454ad9681cc5a',
    messagingSenderId: '960084846767',
    projectId: 'finance-c2c0d',
    authDomain: 'finance-c2c0d.firebaseapp.com',
    storageBucket: 'finance-c2c0d.firebasestorage.app',
    measurementId: 'G-84K2TZE8WM',
  );
}
